name: Jira CI/CD Integration

on:
  pull_request:
    types:
      - closed

jobs:
  update-jira-and-slack:
    if: github.event.pull_request.merged == true
    name: Update Jira & Notify Slack
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Jira Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: https://student-team-tyqvtyie.atlassian.net
        JIRA_USER_EMAIL: 22110369@student.hcmute.edu.vn
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Extract Issue Key from Pull Request Title
      id: extract
      run: |
        echo "🔎 Extracting issue key from PR title: ${{ github.event.pull_request.title }}"
        ISSUE_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]+-[0-9]+')
        echo "✅ Found issue key: $ISSUE_KEY"
        echo "issue=$ISSUE_KEY" >> $GITHUB_OUTPUT

    - name: Transition Jira Issue to Done
      uses: atlassian/gajira-transition@v3
      with:
        issue: ${{ steps.extract.outputs.issue }}
        transition: "Done"

    - name: Notify Slack
      if: ${{ steps.extract.outputs.issue != '' }}
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": ":white_check_mark: Jira issue *${{ steps.extract.outputs.issue }}* has been closed after PR was merged!"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
