name: Update Redmine Status on Pull Request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, closed]

jobs:
  update_redmine_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Cần lịch sử đầy đủ cho việc so sánh commit

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.8' # Thay đổi nếu cần

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Update Redmine Status
        env:
          REDMINE_URL: ${{ secrets.REDMINE_URL }} # URL Redmine của bạn
          REDMINE_API_KEY: ${{ secrets.REDMINE_API_KEY }} # API Key Redmine của bạn
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token mặc định của GitHub Actions
        run: ruby .github/workflows/scripts/update_redmine_status.rb "${{ github.event.pull_request.title }}" "${{ github.event.pull_request.body }}" "${{ github.event.pull_request.state }}" "${{ github.event.pull_request.merged }}" "${{ github.event.pull_request.html_url }}" "${{ github.event.pull_request.head.ref }}" "${{ github.event.pull_request.base.ref }}" "${{ github.repository }}"
